apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagens
  namespace: backend

spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi