apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: primeiro-pv
          mountPath: /volume-dentro-do-container   

  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - clusterkind-worker
        