apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
parameters:
    type: pd-standard
    fstype: ext4

# FUNCIONA PARA O SCHEDULING DO POD