kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: clusterbackup

nodes:
  - role: control-plane
    #image: OTHERIMAGE
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    # - |
    #   kind: ClusterConfiguration
    #   apiServer:
    #       extraArgs:
    #         encryption-provider-config: "/etc/kubernetes/encryptionvolume/encryption.yaml"
    #       extraVolumes:
    #         - name: "encryptionvolume"
    #           hostPath: "/etc/kubernetes/encryptionvolume"
    #           mountPath: "/etc/kubernetes/encryptionvolume"
    #           readOnly: true
    #           pathType: DirectoryOrCreate
    extraMounts:
    - hostPath: /home/matheusoliveira/Opus/Kubernetes/Projeto/utils/encryptionvolume
      containerPath: /etc/kubernetes/encryptionvolume
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    - containerPort: 30100
      hostPort: 30100
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30101
      hostPort: 30101
      listenAddress: "0.0.0.0"
      protocol: TCP
    #labels:
    #  tier: frontend
  - role: worker
  - role: worker