apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: backend
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80
      nodePort: 30101
  selector:
    app: backend