apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80
      nodePort: 30100
  selector:
    app: frontend